steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/pip'
    args: ['install', '-r', 'requirements.txt']

  # Step 2: Run tests
  - name: 'gcr.io/cloud-builders/python'
    args: ['-m', 'pytest']

  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA', '.']

  # Step 4: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA']

  # Step 5: Deploy the image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'run', 'deploy', '$REPO_NAME',
           '--image', 'gcr.io/$PROJECT_ID/$REPO_NAME:$COMMIT_SHA',
           '--platform', 'managed',
           '--region', 'europe-west3',
           '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY
  
substitutions:
  _REPO_NAME: 'API-PYTHON'
timeout: '1200s'