steps:
  # Step 1: Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['install']
    dir: './'  # Adjust to the correct directory if needed

  # Step 2: Run tests
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: 'npm'
    args: ['run', 'test']
    dir: './'

  # Step 3: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/YOUR_REPO_NAME/$REPO_NAME:$COMMIT_SHA', '.']
    dir: './'

  # Step 4: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/data-case-moritz-opitz/moritz-artifacts/python-api:$COMMIT_SHA']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'