name: Build and Push Docker Image to Google Artifact Registry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Decode and set the service account key (optional but recommended)
    - name: Decode and set service account key
      run: echo ${{ secrets.SERVICE_KEY64 }} | base64 --decode > $HOME/gcloud-key.json

    # Step 3: Set up Docker Build and Push using the Base64-encoded key
    - name: Build Image and Push to Google Artifact Registry
      uses: docker/build-push-action@v2
      env:
        SERVICE_KEY64: ${{ secrets.SERVICE_KEY64 }}  # The encoded service account key
      with:
        credentials_json: $SERVICE_KEY64  # Use the Base64-encoded service account key
        context: .
        push: true
        tags: europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/moritz-artifacts/my-image:latest
