name: Build and Push Docker Image to Google Artifact Registry

on:
  push:
    paths:
      - 'api/**'    # only trigger when files in 'api/' are modified
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # step 1: check out repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # step 2: authenticate using google-github-actions/auth
    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.SERVICE_KEY64 }}"  # Use the Base64-encoded service account key
    
    # step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # step 4: authenticate docker to use artifact registry
    - name: Authenticate Docker for Artifact Registry
      run: |
        gcloud auth configure-docker europe-west3-docker.pkg.dev

    # step 5: build Docker image
    - name: Build Docker image
      run: |
        docker build -t europe-west3-docker.pkg.dev/data-case-moritz-opitz/moritz-artifacts/python-api:$GITHUB_SHA api/

    # step 6: run tests (customize this to your application)
    - name: Run Tests
      run: |
        docker run europe-west3-docker.pkg.dev/data-case-moritz-opitz/moritz-artifacts/python-api:$GITHUB_SHA pytest

    # step 7: push Docker image
    - name: Push Docker image
      if: success()
      run: |
        docker push europe-west3-docker.pkg.dev/data-case-moritz-opitz/moritz-artifacts/python-api:$GITHUB_SHA
