name: Build and Push Docker Image to Google Artifact Registry

# Trigger the workflow only when changes are detected in the 'api/' folder
on:
  push:
    paths:
      - 'api/**'    # Trigger only when files in 'api/' are modified
    branches:
      - main

  pull_request:
    paths:
      - 'api/**'    # Trigger for pull requests that modify files in 'api/'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate using google-github-actions/auth
    - id: "auth"
      uses: "google-github-actions/auth@v2"
      with:
        credentials_json: "${{ secrets.SERVICE_KEY64 }}"  # Use the Base64-encoded service account key

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    # Step 4: Authenticate Docker to use Artifact Registry
    - name: Authenticate Docker for Artifact Registry
      run: |
        gcloud auth configure-docker europe-west3-docker.pkg.dev

    # Step 5: Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: api/.  # Set the context to the 'api/' folder where the Dockerfile is located
        push: true
        tags: europe-west3-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/moritz-artifacts/python-api:latest
