name: Build and Push Docker Image to Artifact Registry

# Trigger the workflow only when changes are detected in the 'api/' folder
on:
  push:
    paths:
      - 'api/**'    # Trigger only when files in 'api/' are modified
    branches:
      - main

  pull_request:
    paths:
      - 'api/**'    # Trigger for pull requests that modify files in 'api/'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 3: Set up Google Cloud SDK
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Step 4: Authenticate Docker to use Artifact Registry
    - name: Authenticate Docker for Artifact Registry
      run: |
        gcloud auth configure-docker europe-west3-docker.pkg.dev

    - name: Build Image and run tests
      uses: docker/build-push-action@v2
      env:
        SERVICE_KEY64: ${{ secrets.SERVICE_KEY64 }}
      with:
        credentials_json: $SERVICE_KEY64
        context: .
        push: true
        tags: europe-west3-docker.pkg.dev/data-case-moritz-opitz/moritz-artifacts/python-api:latest
        build-args: |
          SERVICE_KEY64